spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fisioterapia
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
        auto: update
